question_data = [
    {"category": "Sports", "type": "multiple", "difficulty": "easy",
     "question": "In golf, what name is given to a hole score of two under par?",
     "correct_answer": "Eagle",
     "incorrect_answers": ["Birdie", "Bogey", "Albatross"]},
    {"category": "Sports", "type": "multiple", "difficulty": "easy",
     "question": "Which country will host the 2020 Summer Olympics?",
     "correct_answer": "Japan",
     "incorrect_answers": ["China", "Australia", "Germany"]},
    {"category": "Sports", "type": "boolean", "difficulty": "easy",
     "question": "Roger Federer is a famous soccer player.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Sports", "type": "multiple", "difficulty": "easy",
     "question": "What year did the New Orleans Saints win the Super Bowl?",
     "correct_answer": "2010",
     "incorrect_answers": ["2008", "2009", "2011"]},
    {"category": "Sports", "type": "multiple", "difficulty": "easy",
     "question": "When was the first official international game played?",
     "correct_answer": "1872",
     "incorrect_answers": ["1880", "1863", "1865"]},
    {"category": "Sports", "type": "multiple", "difficulty": "easy",
     "question": "Which player holds the NHL record of 2,857 points?",
     "correct_answer": "Wayne Gretzky",
     "incorrect_answers": ["Mario Lemieux ", "Sidney Crosby",
                           "Gordie Howe"]},
    {"category": "Sports", "type": "multiple", "difficulty": "easy",
     "question": "What is the name of Manchester United&#039;s home stadium?",
     "correct_answer": "Old Trafford",
     "incorrect_answers": ["Anfield", "City of Manchester Stadium",
                           "St James Park"]},
    {"category": "Sports", "type": "multiple", "difficulty": "easy",
     "question": "Who did Steven Gerrard win the Champions League with?",
     "correct_answer": "Liverpool",
     "incorrect_answers": ["Real Madrid", "Chelsea", "Man City"]},
    {"category": "Sports", "type": "multiple", "difficulty": "easy",
     "question": "&quot;Stadium of Light&quot; is the home stadium for which soccer team?",
     "correct_answer": "Sunderland FC",
     "incorrect_answers": ["Barcelona FC", "Paris Saints-Germain",
                           "Manchester United"]},
    {"category": "Sports", "type": "multiple", "difficulty": "easy",
     "question": "Who won the UEFA Champions League in 2017?",
     "correct_answer": "Real Madrid C.F.",
     "incorrect_answers": ["Atletico Madrid", "AS Monaco FC",
                           "Juventus F.C."]}
]
